eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8769
spring:
  application:
    name: sun-zuul
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: sun-ribbon
    api-b:
      path: /api-b/**
      serviceId: sun-feign
    uaa:
        path: /uaa/**
        sensitiveHeaders: "*"
        serviceId: sun-auth
    order:
          path: /accounts/**
          sensitiveHeaders: "*"
          serviceId: sun-account
          add-proxy-headers: true
security:
  oauth2:
    client:
      access-token-uri: http://localhost:${server.port}/uaa/oauth/token
      user-authorization-uri: http://localhost:${server.port}/uaa/oauth/authorize
      client-id: webapp
    resource:
      user-info-uri: http://localhost:${server.port}/uaa/user
      prefer-token-info: false